/*
 * generated by Xtext 2.12.0
 */
package ai.ivex.specdsl.ide

import ai.ivex.specdsl.SpecLangRuntimeModule
import ai.ivex.specdsl.SpecLangStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SpecLangIdeSetup extends SpecLangStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SpecLangRuntimeModule, new SpecLangIdeModule))
	}
	
}
