/*
 * generated by Xtext 2.12.0
 */
package ai.ivex.specdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SpecLangRuntimeModule extends AbstractSpecLangRuntimeModule {
}
