/*
 * generated by Xtext 2.12.0
 */
package ai.ivex.specdsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class SpecLangWebModule extends AbstractSpecLangWebModule {
}
