/*
 * generated by Xtext 2.12.0
 */
package ai.ivex.specdsl.tests

import ai.ivex.specdsl.specLang.Model
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(SpecLangInjectorProvider)
class SpecLangParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		Assert.assertTrue(true)
	}
}
